name: Build

on:
  workflow_call:


jobs:
  test:
    name: Run build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run build
        run: |
          echo "Building..."
