name: Deploy

on:
  push:
    branches:
      - dev
      - qa
      - stage
      - hotfix
      - prod

jobs:

  deploy:
    name: deploy
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    environment: nonprod

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Print the contex
        # shell: bash
        # env:
        #   CUSTOM_ENV_VAR: ${{ env.CUSTOM_ENV_VAR }}
        run: env

      - name: Print the var
        shell: bash
        env:
          CUSTOM_ENV_VAR: ${{ env.CUSTOM_ENV_VAR }}
        run: echo "$CUSTOM_ENV_VAR"
