name: Deploy

on:
  pull_request:
    branches:
      - dev
      - qa
      - stage
      - hotfix
      - prod
    types: [closed]

jobs:

  deploy:
    name: deploy
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    # environment: ${{ github.ref_name =  }}

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Print the var
        shell: bash
        run: "echo $CUSTOM_ENV_VAR"
