name: Deploy

on:
  push:
    branches:
      - dev
      - qa
      - stage
      - hotfix
      - prod

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Some check on branch
        id: branch_check
        run: |
          echo "Running on branch ${{ github.ref_name }}"
          if [ "${{ github.ref_name }}" = "prod" ]; then
            echo "::set-output name=env_name::prod"
          else
             echo "::set-output name=env_name::nonprod"
          fi
    outputs:
      env_name: ${{ steps.branch_check.outputs.env_name }}

  deploy:
    name: deploy
    needs: [build]
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    environment:
      name: ${{ needs.build.outputs.env_name }}

    steps:

      - name: Checkout git repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup java
        uses: ./.github/actions/setup-java

      - name: Print the var
        shell: bash
        # env:
        #   CUSTOM_ENV_VAR: ${{ env.CUSTOM_ENV_VAR }}
        run: echo "${{ vars.CUSTOM_ENV_VAR }}"

