name: Test

on:
  workflow_call:
  pull_request:
    branches: [prod, dev, qa, stage, main, 'dev-*']


jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run tests
        run: |
          echo "Running tests"

      - name: Publish Unit Test Results
        run: |
          echo "Publishing results"
